package com.tanrice.studentregistrationmanagementsystem.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tanrice.studentregistrationmanagementsystem.basedata.User;
import com.tanrice.studentregistrationmanagementsystem.basedata.UserProject;

import com.tanrice.studentregistrationmanagementsystem.dao.UserDao;
import com.tanrice.studentregistrationmanagementsystem.dao.UserProjectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig userProjectDaoConfig;

    private final UserDao userDao;
    private final UserProjectDao userProjectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userProjectDaoConfig = daoConfigMap.get(UserProjectDao.class).clone();
        userProjectDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        userProjectDao = new UserProjectDao(userProjectDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(UserProject.class, userProjectDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        userProjectDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UserProjectDao getUserProjectDao() {
        return userProjectDao;
    }

}
