package com.tanrice.studentregistrationmanagementsystem.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.tanrice.studentregistrationmanagementsystem.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property UserName = new Property(1, String.class, "userName", false, "USER_NAME");
        public final static Property Userpwd = new Property(2, String.class, "userpwd", false, "USERPWD");
        public final static Property Age = new Property(3, int.class, "age", false, "AGE");
        public final static Property Gender = new Property(4, String.class, "gender", false, "GENDER");
        public final static Property Name = new Property(5, String.class, "name", false, "NAME");
        public final static Property School = new Property(6, String.class, "school", false, "SCHOOL");
        public final static Property Academy = new Property(7, String.class, "academy", false, "ACADEMY");
        public final static Property RegistrationProject = new Property(8, int.class, "registrationProject", false, "REGISTRATION_PROJECT");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"USER_NAME\" TEXT," + // 1: userName
                "\"USERPWD\" TEXT," + // 2: userpwd
                "\"AGE\" INTEGER NOT NULL ," + // 3: age
                "\"GENDER\" TEXT," + // 4: gender
                "\"NAME\" TEXT," + // 5: name
                "\"SCHOOL\" TEXT," + // 6: school
                "\"ACADEMY\" TEXT," + // 7: academy
                "\"REGISTRATION_PROJECT\" INTEGER NOT NULL );"); // 8: registrationProject
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String userpwd = entity.getUserpwd();
        if (userpwd != null) {
            stmt.bindString(3, userpwd);
        }
        stmt.bindLong(4, entity.getAge());
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(5, gender);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(6, name);
        }
 
        String school = entity.getSchool();
        if (school != null) {
            stmt.bindString(7, school);
        }
 
        String academy = entity.getAcademy();
        if (academy != null) {
            stmt.bindString(8, academy);
        }
        stmt.bindLong(9, entity.getRegistrationProject());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String userpwd = entity.getUserpwd();
        if (userpwd != null) {
            stmt.bindString(3, userpwd);
        }
        stmt.bindLong(4, entity.getAge());
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(5, gender);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(6, name);
        }
 
        String school = entity.getSchool();
        if (school != null) {
            stmt.bindString(7, school);
        }
 
        String academy = entity.getAcademy();
        if (academy != null) {
            stmt.bindString(8, academy);
        }
        stmt.bindLong(9, entity.getRegistrationProject());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userpwd
            cursor.getInt(offset + 3), // age
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // gender
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // school
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // academy
            cursor.getInt(offset + 8) // registrationProject
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setUserName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserpwd(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAge(cursor.getInt(offset + 3));
        entity.setGender(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSchool(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAcademy(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setRegistrationProject(cursor.getInt(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
