package com.tanrice.studentregistrationmanagementsystem.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.tanrice.studentregistrationmanagementsystem.basedata.UserProject;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_PROJECT".
*/
public class UserProjectDao extends AbstractDao<UserProject, Long> {

    public static final String TABLENAME = "USER_PROJECT";

    /**
     * Properties of entity UserProject.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property StudentNumber = new Property(0, Long.class, "studentNumber", true, "_id");
        public final static Property Json = new Property(1, String.class, "json", false, "JSON");
    }


    public UserProjectDao(DaoConfig config) {
        super(config);
    }
    
    public UserProjectDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_PROJECT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: studentNumber
                "\"JSON\" TEXT);"); // 1: json
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_PROJECT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserProject entity) {
        stmt.clearBindings();
 
        Long studentNumber = entity.getStudentNumber();
        if (studentNumber != null) {
            stmt.bindLong(1, studentNumber);
        }
 
        String json = entity.getJson();
        if (json != null) {
            stmt.bindString(2, json);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserProject entity) {
        stmt.clearBindings();
 
        Long studentNumber = entity.getStudentNumber();
        if (studentNumber != null) {
            stmt.bindLong(1, studentNumber);
        }
 
        String json = entity.getJson();
        if (json != null) {
            stmt.bindString(2, json);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserProject readEntity(Cursor cursor, int offset) {
        UserProject entity = new UserProject( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // studentNumber
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // json
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserProject entity, int offset) {
        entity.setStudentNumber(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setJson(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserProject entity, long rowId) {
        entity.setStudentNumber(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserProject entity) {
        if(entity != null) {
            return entity.getStudentNumber();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserProject entity) {
        return entity.getStudentNumber() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
